name: Build and Deploy React App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      CI: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy updated build
        run: |
          # Copy new build files to the persistent build directory
          cp -R build/* /home/actions/my-react-app/build/
          # Restart the service so it serves the new version
          sudo systemctl restart react-app.service
